### ISSUE TITLE
Hide entries with empty quantites

### ISSUE THREAD

**Issue by MannyC** [will123195/cryptonetworth#4]
I was playing with the option of hiding some of the rows, as I'm not generally interested in all of them and they can get in the way of the ones that I want to see.

https://github.com/MannyC/cryptonetworth/commit/0e8751cbb5a7c0d873b04d258611b4124439160a

I'll clean it up and put in a PR if it's something you'd go for.

Also, is there no way to get your `bleh` tool to output a fully static version of the site?  My intention was to commit the dist folder to github and then use rawgit to view the results but the `bleh build` doesn't seem to create the necessary html pages.

**Comment by will123195** [comment]
Nice! Yes, this is a much-needed feature, a PR would be awesome! 

I've been thinking about a way to make the page load faster (i.e. on mobile) by not downloading the empty rows. But for now, this looks great!

In Chrome, you can click "File > Save Page As" which will give you the static html file you're looking for.

**Comment by will123195** [comment]
But the static html file won't help since it's rendered server-side... the prices won't update.

**Comment by MannyC** [comment]
Great, I'll put one together for discussion.

Re: static page, ahh I didn't look closely enough and assumed the coinmarketcap api was being queried directly from the client, and that all the handlebars templating was happening on the client too.
